### ISSUE TITLE
#BUG: Not able to  Create the sku: Standard Tier Container registry.

### ISSUE THREAD

**Issue by Annavar-satish** [imjoseangel/terraform-azurerm-acr#130]
# SUMMARY
While Creating the SKU with Standard the validation is falling and not able to create the Standard acr_registry
[issue_at](https://github.com/imjoseangel/terraform-azurerm-acr/blob/devel/variables.tf#L25)
```
    condition     = contains(["Basic", "Standard ", "Premium"], var.sku) 
```
in the above condition,  Standard got a space before the double quotes ended that resulting in this issue and not able to create the Standard Tier container-registry.

## ISSUE TYPE

- Bug Report
- Issue Report

## COMPONENT NAME

 Error: Invalid value for variable
 
   on main.tf line 6, in module "acr_cognyx":
    6:   sku                           = var.sku
     ├────────────────
     │ var.sku is "Standard"
 
 ERROR: Invalid SKU Tier must be one of Basic, Standard or Premium.
 
 This was checked by the validation rule at .terraform/modules/acr_cognyx/variables.tf:24,3-13.
## VERSION
```
  source  = "imjoseangel/acr/azurerm"
  version = "22.2.6"
  terraform version = 1.7.5

```

## CONFIGURATION

```paste below
module "acr_registry" {
  source  = "imjoseangel/acr/azurerm"
  version = "22.2.6"
  name                          = var.acr_name
  resource_group_name           = var.rg_name
  sku                           = "Standard"
  location                      = var.location
  admin_enabled                 = true
  retention_policy = {
    days    = 5
    enabled = true
  }

}

```

## STEPS TO REPRODUCE
create the Standard tier using the above module.

**Comment by imjoseangel** [comment]
Fixed #131
